version: '3.6'

services:

  smoke:
    image: particlekit/ldap-client
    container_name: smoke
    depends_on:
      - ldap
    command: ldapsearch -x -H ldap://ldap -D "cn=admin,dc=acturus,dc=net" -w admin -b dc=acturus,dc=net
  app:
    image: acturus/example-12factor-node
    container_name: app
    environment:
      - 'MONGO_URL=mongodb://root:password@mongo/admin'
      - 'LDAP_URL=ldap://ldap'
      - 'LDAP_USER=cn=admin,dc=acturus,dc=net'
      - 'LDAP_PASSWORD=admin'
      - 'HOST=0.0.0.0'
      - 'PORT=3000'
    command: "node /usr/src/app/server.js"
    volumes:
      - ./src:/app
    depends_on:
      - mongo
      - ldap
    ports:
      - "3000:3000"
  ldap:
    image: osixia/openldap
    container_name: ldap
    environment:
      - 'LDAP_ORGANISATION=Acturus'
      - 'LDAP_DOMAIN=acturus.net'
    volumes:
      - ./bootstrap/ldif/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command:
      - "--copy-service"
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_DATABASE=app'
    volumes:
      - ./bootstrap/mongo:/docker-entrypoint-initdb.d:ro
